config/routes.rb
RailsProject::Application.routes.draw do

  get "comments/create"

  get "/admin" => 'static_pages#admin'
  get "/about" => 'static_pages#about', as: :about

  get "/logout" => 'sessions#destroy', as: :logout
  get "/signup" => 'users#new', as: :signup
  root :to => 'static_pages#index'

  get "/around_me" => 'items#around_me', as: :around_me
  get "/update_location" => 'locations#new_geotag', as: :geotag

  post "/search" => 'items#search', as: :search

  
  resources :sessions
  resources :users
  resources :items
  resources :addresses

  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :public
  belongs_to :commentable, polymorphic: true

  belongs_to :sender, class_name: "User"


  def public?
    return self.public
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new(content: params[:comment][:content], public: params[:comment][:public])
    comment.sender = current_user
    item = Item.find(params[:comment][:item_id])
    item.comments << comment
    redirect_to item_path(item)
  end

  def destroy
    comment = Comment.find(params[:id])
    item = Item.find(comment.commentable_id)
    comment.destroy
    redirect_to item_path(item)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.haml
%ul#comments
  - comments.each do |comment|
    - if can? :read, comment and comment.id 
      %li.comment
        /= image_tag comment.sender.image.url if comment.sender.image
        %p= comment.content
        .author
          = comment.sender.email if comment.sender
          %br
          = link_to "Delete Comment", comment_path(comment), method: :delete if can? :destroy, comment


:sass

  ul#comments
    padding: 0
    margin: 0
    li.comment
      list-style-type: none
      width: 100%
      border-bottom: 1px solid #dddddd
      background-color: white
      p
        padding: 10px
      .author
        text-align: right
      &:nth-child(2n)
        background-color: #f9f9f9
      img 
        height: 100px
        width: 100px
      

app/views/comments/_form.haml
= form_for comment do |f|
  - if comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(comment.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - comment.errors.full_comments.each do |msg|
          %li= msg

  = f.hidden_field :item_id, value: @item.id


  .field
    = f.label :content, "New Comment"
    = f.text_area :content, rows:"3", style:'width:100%'
  .field
    = f.radio_button :public, 1, checked: true
    Public
    = f.radio_button :public, 0
    Private
  .actions
    = f.submit 'Send', class: "pull-right btn btn-success"