config/routes.rb
RailsProject::Application.routes.draw do

  get "comments/create"

  get "/admin" => 'static_pages#admin'
  get "/about" => 'static_pages#about', as: :about

  get "/logout" => 'sessions#destroy', as: :logout
  get "/signup" => 'users#new', as: :signup
  root :to => 'static_pages#index'

  get "/around_me" => 'items#around_me', as: :around_me
  get "/update_location" => 'locations#new_geotag', as: :geotag

  post "/search" => 'items#search', as: :search

  
  resources :sessions
  resources :users
  resources :items
  resources :addresses

  resources :comments, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :image, :first_name, :last_name


  has_one :image, as: :imageable, dependent: :destroy # Profile picture
  has_many :items, dependent: :destroy
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :locations, through: :addresses

  has_many :comments, through: :items

  validates :email,
    presence: true,
    uniqueness: true,
    format:{with:EMAIL_REGEX}

  validates :password,
    presence:true, on: :create,
    confirmation:true

  validates :password, 
    format:{with:PASSWORD_REGEX, message: "Password must be at least 8 characters long"}, on: :create,
    if: lambda{ Rails.env.production? }

 accepts_nested_attributes_for :image
 attr_accessible :image_attributes

  def first_name=(value)
    write_attribute :first_name, value.capitalize
  end

  def last_name=(value)
    write_attribute :last_name, value.capitalize
  end

  def current_location
    return Location.where("locatable_type = ? AND locatable_id = ?", self.class.to_s, self.id).last
  end

  def current_location=(value)
    if self.current_location.nil?
      location = Location.new(latitude: value.latitude, longitude: value.longitude)
      location.locatable_type = self.class.to_s
      location.locatable_id = self.id
      location.save
    else
      self.current_location.update_attributes(:latitude =>  value.latitude, :longitude => value.longitude)
    end
    save!
  end

  def locations
    locations = []
    locations << Location.where("locatable_type = ?", self.class.to_s).first 
    self.addresses.each do |address|
      locations << address.location
    end
    return locations
  end

  def time_since_last_update
    return Time.now - current_location.updated_at
  end

  def last_location_is_good?
    return time_since_last_update < 3600 ? true : false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #skip_before_filter :require_login, only:[:new, :create]
  skip_load_and_authorize_resource only:[:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path, notice:"User Created, go ahead and log in"
    else
      @user.build_image
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @items = @user.items
    @locations = []
    @user.addresses.each{|address|
      @locations << address.location
    }
  end

  def edit
    @user = current_user
    @user.build_image if @user.image.nil?
  end

  def update
    @user = current_user
    if @user.update_attributes(params[:user])
      redirect_to user_path(current_user)
    else
      @user.build_image
      render :edit
    end
    
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.haml
= form_for @user, html_options:{multipart:true} do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  .field
    = f.fields_for :image do |b|
      = image_tag @user.image.url, id: "profile_picture" unless @user.image.id.nil?
      %br
      = b.label :url, "Profile Picture"
      = b.file_field :url
  
  .field
    = f.label :first_name
    = f.text_field :first_name

  .field
    = f.label :last_name
    = f.text_field :last_name

  .actions= f.submit "Submit"

app/views/users/edit.haml
.container
  .span12
    %h1
      Editing the profile page

    = render partial:"form"

app/views/users/new.haml
.container
  .row
    .span12 
      %h1 Signup
          
      = form_for @user do |f|
        - if @user.errors.any?
          .error_messages
            %h2 Form is invalid
            %ul
              - for message in @user.errors.full_messages
                %li= message
        .field
          = f.label :email
          = f.text_field :email
        .field
          = f.label :password
          = f.password_field :password
        .field
          = f.label :password_confirmation
          = f.password_field :password_confirmation
        .actions= f.submit "Signup"

app/views/users/show.haml
.container 
  .row
    .span12
      %h1 
        Profile

      .row
        .span5
          - if !@user.image.nil?
            = image_tag @user.image.url, id: "profile_picture"

          %table{width: "100%"}
            %th
            %tbody
              %tr
                %th First Name
                %td= @user.first_name || "Not Set"

              %tr
                %th Last Name
                %td= @user.last_name || "Not Set"

              %tr
                %th Email
                %td= @user.email

          %br

          = link_to "Edit My Profile", edit_user_path(@user) if can? :update, @user

        .span7

          = render partial:"layouts/map", locals:{place: @user.locations} if @user == current_user

      - if can? :read, @user.addresses.first
        %h3 My addresses
        
        .row
          .span12.address_list
            - @user.addresses.each do |address|
              .address_item
                %strong= address.name
                = address.number_and_street
                %br
                = address.city
                %br
                = "#{address.state}, #{address.zip_code}"
                %br
                = link_to "Delete Address", address_path(address), method: :delete if can? :destroy, address

      .row
        %hr
        .span5

          = render partial:"addresses/form" if @user == current_user

:javascript
  $(document).ready(function(){
    get_location();
    function get_location(){
      if (navigator.geolocation){
        navigator.geolocation.getCurrentPosition(show_pos, show_error);
      }
    }
    function show_pos(position){
      options = {
      url: "/update_location",
      type: "get",
      data: {
        "location[latitude]": position.coords.latitude,
        "location[longitude]": position.coords.longitude
        }
      };
      console.log(options.data);
      $.ajax(options);
    }

    function show_error(){}
  });