config/routes.rb
RailsProject::Application.routes.draw do

  get "comments/create"

  get "/admin" => 'static_pages#admin'
  get "/about" => 'static_pages#about', as: :about

  get "/logout" => 'sessions#destroy', as: :logout
  get "/signup" => 'users#new', as: :signup
  root :to => 'static_pages#index'

  get "/around_me" => 'items#around_me', as: :around_me
  get "/update_location" => 'locations#new_geotag', as: :geotag

  post "/search" => 'items#search', as: :search

  
  resources :sessions
  resources :users
  resources :items
  resources :addresses

  resources :comments, only: [:create, :destroy]
end

app/models/item.rb
class Item < ActiveRecord::Base

  attr_accessible :description, :name, :location_id, :category_ids, :location

  belongs_to :user

  has_many :categorizations
  has_many :categories, through: :categorizations

  has_many :images, as: :imageable, dependent: :destroy

  has_one :location, as: :locatable, dependent: :destroy

  has_many :comments, as: :commentable, dependent: :destroy


  validates :name,
    presence:true

  #searchable do 
  #  text :name, boost: 10
  #  text :description, boost: 7
  #  integer :location_id
  #end

  def self.item_search(query, location=nil, range=10)
    #self.search do
    #  fulltext query
    #  with(:location_id, Location.near(location, range).map{|x| x.id})
    #end
    Item.where("name @@ :q OR description @@ :q", q: "%#{query}%").where(id: Location.near(location, range).map{|x| x.id}.to_a)
  end

  def self.near(location=nil, range=10)
    Item.where(location_id: Location.near(location, range).map{|x| x.id}.to_a)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  #need the following line, otherwise, it breaks for some reason
  skip_load_and_authorize_resource only:[:create]#except:[:around_me]

  def new
    @item = Item.new
    @item_locations = current_user.current_location.nil? ? [] : [["Current Location", current_user.current_location.id]] 
    @item_locations += current_user.addresses.map{|x| [x.name, x.location.id]}
  end

  def create
    loc = Location.find(params[:item][:location])
    b = loc.dup 
    @item = Item.new(name: params[:item][:name], description: params[:item][:description], category_ids: params[:item][:category_ids])
    @image = Image.create(url: params[:item][:image]) unless params[:item][:image].nil?
    @item.images << @image unless @image.nil?
    if @item.save
      b.save
      @item.location_id = b.id
      @item.location = b
      @item.save
      current_user.items << @item
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.update_attributes(name: params[:item][:name], description: params[:item][:description], category_ids: params[:item][:category_ids])
    @item.images << Image.create(url: params[:item][:image]) unless params[:item][:image].nil? 

    redirect_to item_path(@item)
  end

  def edit
    @item = Item.find(params[:id])
    @item_locations = current_user.current_location.nil? ? [] : [["Current Location", current_user.current_location.id]] 
    @item_locations += current_user.addresses.map{|x| [x.name, x.location.id]}
  end
  def show
    @item = Item.find(params[:id])
    #@item =  Item.joins(:images).where("items.id = ? OR images.imageable_id = ? AND images.imageable_type = 'Item'", params[:id], params[:id]).select("items.*, images.url as image_url").first
  end

  def index
    @items = current_user.items
    @item = Item.new
  end

  def destroy
    item = Item.find(params[:id])
    if current_user.items.include? item
      item.destroy
      redirect_to items_path
    else
      redirect_to root_path, alert: "You do not have the right"
    end 
  end

  def around_me
    if params[:categories].nil?
      @categories = Category.all.map{|x| x.id.to_s}
    else
      @categories = params[:categories].split(",")
    end 

    @items = Item.near(last_location, 2).sample(25)

    @items = @items.map{|item| item if (item.categorizations.pluck(:category_id).map{|x| x.to_s} - @categories).size < item.categorizations.pluck(:category_id).map{|x| x.to_s}.size }.compact

    respond_to do |format|
      format.html
      format.js { render layout: false }
    end
  end

  def search
    @query = params[:search]
    @items = Item.item_search(@query, last_location, params[:range])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.haml
= form_for @item do |f|
  .span12 
    - if @item.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @item.errors.full_messages
            %li= message

  .row
    .span3
      %h3 Item Info
      .field
        = f.label :name
        = f.text_field :name

      .field
        = f.label :description
        = f.text_area :description, rows: "3" 

      .field
        = f.label :location
        = f.select :location, @item_locations 


      .actions
        = f.submit "Submit", class: "btn btn-success"

    .span3
      %h3 Categories
      .field 
        - Category.all.each do |category|
          = check_box_tag "item[category_ids][]", category.id, @item.category_ids.include?(category.id)
          = category.name
          %br

    .span3
      %h3 Availabilities



    .span3
      %h3 Pictures
      .item_picture_list
        - @item.images.each do |image|
          = image_tag image.url, class: "item_tile"

      .field
        = f.label :image, "Add Picture"
        = f.file_field :image

app/views/items/_items.haml
- items.each do |item|
  - if item.images.empty?
    .item_picture
      %h1= link_to item.name, item_path(item)
      %p= item.description
  - else 
    .item_picture{style:"background: url(\"#{item.images.first.url}\"); background-size: 200px 200px; background-size: cover"}
      %h1= link_to item.name, item_path(item)
      %p= item.description

app/views/items/around_me.haml
.container
  .row 
    .span12
      %h1 
        Around Me
    

      - Category.all.each do |category|
        = check_box_tag category.name.downcase, category.id, checked:true
        = category.name
      %h3
        We found this around you
  .row
    .span12

      .item_picture_list
        = render partial:"items", locals:{items: @items}

  .row
    .span12
      .spinner{style:"display:none"}
        = image_tag "ajax-loader.gif"

app/views/items/around_me.js.erb
$('.item_picture_list').append('<%= j render partial:"items", locals:{items: @items}%>')

app/views/items/edit.haml
.container
  .row
    .span12 
      %h1 Editing an item
      = render partial:"form"

app/views/items/index.haml
.container
  .row 
    .span6 
      %h2 Your items
      %h3 
        You currently have 
        = pluralize(@items.length, "item")
        listed

      %table{width: "100%"}
        - @items.each do |item|
          %tr
            %td= item.name
            %td
              = link_to "View", item_path(item.id), class: "btn btn-primary"
              \|
              = link_to "Edit", edit_item_path(item.id), class: "btn btn-warning"
              \|
              = link_to "Delete", item_path(item.id), method: :delete, class: "btn btn-danger"
        %br

      %br
      %br
      %br

      = link_to "New Item", new_item_path, class: "btn btn-success"

app/views/items/new.haml
.container
  .row
    .span12
      %h3 Add an item

  .row
    .span12
      = render partial:"form"

app/views/items/search.haml
.container
  .row 
    .span12
      %h1 Search for #{@query}

  .row
    .span12
      .item_picture_list
        = render partial:"items", locals:{items: @items}

app/views/items/show.haml
.container
  .row
    .span12 
      %h1 
        Item
        = @item.name

  .row
    .span6 
      .item_picture_list
        - @item.images.each do |image|
          = image_tag image.url, class: "item_tile"

    .span6 
      = render partial:"layouts/map", locals:{place:[@item.location]}

  .row
    .span12
      %h2 Item Information
  .row
    .span4
      %h4 Data
      %strong Name: 
      = @item.description
      %br
      %strong Description:
      = @item.description

    .span4
      .item_categories
        %h4 Categories
        %ul
          - @item.categories.each do |category|
            %li= category.name
    .span4
      %h4 Availabilites
  .row
    .span12
      = link_to "Edit", edit_item_path(@item.id), class: "btn btn-warning" if can? :edit, @item
      = link_to "Delete", item_path(@item.id), {method: :delete, class: "btn btn-danger"} if can? :destroy, @item


  .row
    .span6.offset3
      %h3 Comments
      = render partial: "comments/form", locals:{comment: @item.comments.build}
      %br
      = render partial: "comments/comments", locals:{comments: @item.comments}