config/routes.rb
RailsProject::Application.routes.draw do

  get "comments/create"

  get "/admin" => 'static_pages#admin'
  get "/about" => 'static_pages#about', as: :about

  get "/logout" => 'sessions#destroy', as: :logout
  get "/signup" => 'users#new', as: :signup
  root :to => 'static_pages#index'

  get "/around_me" => 'items#around_me', as: :around_me
  get "/update_location" => 'locations#new_geotag', as: :geotag

  post "/search" => 'items#search', as: :search

  
  resources :sessions
  resources :users
  resources :items
  resources :addresses

  resources :comments, only: [:create, :destroy]
end

app/views/layouts/_map.haml
.cool
  - if !place.empty?
    = gmaps("map_options" => {"zoom" => 10, "auto_zoom" => place.length > 1, id: "map#{place.first.id}"}, 
        "markers" => {"data" => place.to_gmaps4rails}) if !place.first.nil?

app/views/layouts/_nav.haml
%button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", type: "button"}
  %span.icon-bar
  %span.icon-bar
  %span.icon-bar

.nav-collapse.collapse
  / .nav, .navbar-search, .navbar-form, etc
  %ul.nav
    %li= link_to "Nearbuy", root_path, class:"brand"
    - if current_user
      %li 
        = link_to "My Profile", user_path(current_user)


      %li.dropdown
        = link_to "Post", "#", class: "dropdown-toggle", "data-toggle" => "dropdown" 
        %ul.dropdown-menu
          = form_for Item.new do |f|
            .field
              = f.label :name
              = f.text_field :name
            .field
              = f.label :description
              = f.text_area :description, rows: "3" 
            .field
              = f.label :image, "Add Picture"
              = f.file_field :image
            .field
              = f.label :location
              - @item_locations = current_user.current_location.nil? ? [] : [["Last Location", current_user.current_location.id]] 
              - @item_locations += current_user.addresses.map{|x| [x.name, x.location.id]}
              = f.select :location,  @item_locations
            .actions
              = f.submit "Submit", class: "btn btn-success"


      %li 
        = link_to "My Items", items_path
    
      %li 
        = link_to "Around Me", around_me_path

  
  %ul.nav.pull-right
      
    %li 
      = link_to "About", about_path
    %li
      - if !current_user
        %a{href:"#login_modal", "data-toggle" => "modal"}Login
      - else
        = link_to "Logout #{current_user.email}", logout_path
- if current_user 
  = form_tag search_path, class:"navbar-search pull-right" do
    = text_field_tag :search, nil, placeholder:"Search", class: "search-query"
    = select_tag "range", grouped_options_for_select({"Range" => [["1 mile", 1], ["2 miles", 2], ["5 miles", 5]]}, 2), class: "search-query span1"

app/views/layouts/application.haml
!!!
%html
  %head
    %title NearBuy
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    /%link{href: "/assets/BootStrap/bootstrap-responsive.css", rel: "stylesheet"}

  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container
          = render partial:"layouts/nav"
            
    - if !current_user 
      #login_modal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
          %h3#myModalLabel Sign In  
 
        = render partial:"sessions/login"

    .container 
      .row
        .span12 
          - unless flash[:notice].blank?
            .alert
              = flash[:notice]
          - unless flash[:alert].blank?
            .alert.alert-error  
              = flash[:alert]
          
    = yield 

    = content_for :scripts